[package]
name = "yane"
version = "0.1.0"
edition = "2021"
authors = ["vinz <vincent.siles@gmail.com>"]

[dependencies]
lazy_static = "1.4.0"
rand = "=0.7.3"
spin_sleep = "1.1.1"

[dependencies.sdl2]
version = "0.31.0"
default-features = false
# features = ["ttf", "image"]